keywords-file: Data\keywords.csv
competitor-keywords-file: Data\competitor_keywords.txt
page-file:
competitor-files: Data\competitors.txt
rules:
	- 
    slug: applications-segment
        is-keyword: true
        is-url: true
    - 
        slug: applications-block
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: applications-title
        is-keyword: true
        is-url:
    - 
        slug: applications-description-ru
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: applications-description
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: app-segment
        is-keyword: true
        is-url: true
    - 
        slug: app-title
        is-keyword: true
    - 
        slug: app-sub-title-ru
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: app-sub-title
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: app-block-title
        is-keyword: true
    - 
        slug: app-block-description
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: app-about-title
        is-keyword: true
    - 
        slug: app-about-description-ru
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: app-about-description
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: format-segment
        is-keyword: true
        is-url: true
    - 
        slug: format-title
        is-keyword: true
    - 
        slug: format-sub-title
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: format-about
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: format-about-title
        is-keyword: true
    - 
        slug: format-about-description
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    - 
        slug: format-about-how-to-title
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others:
    -  
		slug: format-about-how-to-description
        min-keywords:
        max-keywords:
        min-length:
        max-max:
        max-competitorLength:
        allow-additionParagraph:
        unique:
        competitors-mix:
        check-plagiat:
        is-keyword:
        is-url:
        first-include-others: