keywords-file: Data\keywords.csv
competitor-keywords-file: Data\competitor_keywords.txt
page-file:
competitor-files: Data\competitors.txt
rules:
    - slug: applications-app-title
      ref: app-title
    - slug: applications-app-description
      ref: app-sub-title
	  - slug: app-segment
      is-keyword: true
      is-url: true
    - slug: app-title
      is-keyword: true
    - slug: app-block-title
      is-keyword: true
    - slug: app-about-title
      is-keyword: true
      end-keyword: true
    - slug: app-sub-title
      min-keywords: 1
      max-keywords: 1
      start-keyword: true
      min-length: 50
      max-length: 90
      allow-additionParagraph: true
    - slug: app-about-description
      min-keywords: 1
      max-keywords: 3
      max-length: 150
      max-competitor-length: true
      unique: true
      competitors-mix: true
      first-include-others: true
    - slug: app-format-title
      is-keyword: true
      start-keyword: true
    - slug: app-format-description
      ref: format-sub-title
    - slug: format-segment
      is-keyword: true
      is-url: true
    - slug: format-title
      is-keyword: true
    - slug: format-sub-title
      min-keywords: 1
      max-keywords: 1
      start-keyword: true
      min-length: 50
      max-length: 90
    - slug: format-about-title
      is-keyword: true
      end-keyword: true
    - slug: format-about-description
      min-keywords: 1
      max-keywords: 5
      min-length: 1500
      max-length: 3000
      max-competitor-length: true
      unique: true
      check-plagiat: true
    - slug: format-how-to-title
      is-keyword: true
      end-keyword: true