rules:
    - slug: applications-app-title
      ref: app-title
    - slug: applications-app-description
      ref: app-sub-title
    - slug: app-segment
      is-keyword: true
      is-url: true
    - slug: app-title
      is-keyword: true
      allow-addition-paragraph: false
    - slug: app-block-title
      is-keyword: true
      allow-addition-paragraph: false
    - slug: app-about-title
      is-keyword: true
      end-keyword: true
      allow-addition-paragraph: false
    - slug: app-sub-title
      min-keywords: 1
      max-keywords: 1
      start-keyword: true
      min-length: 50
      max-length: 90
      allow-addition-paragraph: true
    - slug: app-about-description
      min-keywords: 1
      max-keywords: 3
      max-length: 150
      max-competitor-length: true
      allow-addition-paragraph: false
      unique: true
      competitors-mix: true
      first-include-others: true
    - slug: app-format-title
      is-keyword: true
      start-keyword: true
      allow-addition-paragraph: false
    - slug: app-format-description
      ref: format-sub-title
      allow-addition-paragraph: false
    - slug: format-segment
      is-keyword: true
      is-url: true
    - slug: format-title
      is-keyword: true
      allow-addition-paragraph: false
    - slug: format-sub-title
      min-keywords: 1
      max-keywords: 1
      start-keyword: true
      min-length: 50
      max-length: 90
      allow-addition-paragraph: false
    - slug: format-about-title
      is-keyword: true
      end-keyword: true
      allow-addition-paragraph: false
    - slug: format-about-description
      min-keywords: 1
      max-keywords: 5
      min-length: 1500
      max-length: 3000
      allow-addition-paragraph: false
      max-competitor-length: true
      unique: true
      check-plagiat: true
    - slug: format-how-to-title
      is-keyword: true
      end-keyword: true
      allow-addition-paragraph: false
rule-keys:
  - app-segment
  - app-title
  - app-sub-title
  - app-sub-title-ru
  - app-about-title
  - app-about-description-ru
  - app-about-description
  - applications-app-title
  - applications-app-description-ru
  - applications-app-description
  - applications-segment
  - format-segment
  - format-title
  - format-sub-title
  - format-sub-title-ru
  - format-about-title
  - format-about-description-ru
  - format-about-description
  - app-format-title
  - app-format-description-ru
  - app-format-description
  - format-how-to-title
  - format-how-to-description-ru
  - format-how-to-description
keywords-file: keywords.yaml
competitor-keywords-file: competitor_keywords.yaml
competitor-file: competitors.yaml
