keywords-file: Data\keywords.csv
competitor-keywords-file: Data\competitor_keywords.txt
page-file:
competitor-files: Data\competitors.txt
rules:
    - slug: applications-app-title
      min-keywords:
      max-keywords:
      min-length:
      max-max:
      max-competitorLength:
      allow-additionParagraph:
      unique:
      competitors-mix:
      check-plagiat:
      is-keyword:
      is-url:
      first-include-others:
    - slug: applications-app-description
      min-keywords:
      max-keywords:
      min-length:
      max-max:
      max-competitorLength:
      allow-additionParagraph:
      unique:
      competitors-mix:
      check-plagiat:
      is-keyword:
      is-url:
      first-include-others:
	  - slug: app-segment
      is-keyword: true
      is-url: true
    - slug: app-title
      is-keyword: true
    - slug: app-block-title
      is-keyword: true
    - slug: app-about-title
      is-keyword: true
      end-keyword: true
    - slug: app-sub-title
      min-keywords: 1
      max-keywords: 2
      start-keyword: true
      min-length: 50
      max-max: 90
      allow-additionParagraph: true
    - slug: app-about-description
      min-keywords:
      max-keywords:
      min-length:
      max-max:
      max-competitorLength:
      allow-additionParagraph:
      unique:
      competitors-mix:
      check-plagiat:
      is-keyword:
      is-url:
      first-include-others:
    - slug: app-format-title
      min-keywords:
      max-keywords:
      min-length:
      max-max:
      max-competitorLength:
      allow-additionParagraph:
      unique:
      competitors-mix:
      check-plagiat:
      is-keyword:
      is-url:
      first-include-others:
    - slug: app-format-description
      min-keywords:
      max-keywords:
      min-length:
      max-max:
      max-competitorLength:
      allow-additionParagraph:
      unique:
      competitors-mix:
      check-plagiat:
      is-keyword:
      is-url:
      first-include-others:
    - slug: format-segment
      is-keyword: true
      is-url: true
    - slug: format-title
      is-keyword: true
    - slug: format-sub-title
      min-keywords:
      max-keywords:
      min-length:
      max-max:
      max-competitorLength:
      allow-additionParagraph:
      unique:
      competitors-mix:
      check-plagiat:
      is-keyword:
      is-url:
      first-include-others:
    - slug: format-about-title
      is-keyword: true
      end-keyword: true
    - slug: format-about-description
      min-keywords:
      max-keywords:
      min-length:
      max-max:
      max-competitorLength:
      allow-additionParagraph:
      unique:
      competitors-mix:
      check-plagiat:
      is-keyword:
      is-url:
      first-include-others:
    - slug: format-how-to-title
      min-keywords:
      max-keywords:
      min-length:
      max-max:
      max-competitorLength:
      allow-additionParagraph:
      unique:
      competitors-mix:
      check-plagiat:
      is-keyword:
      is-url:
      first-include-others:
    - slug: format-how-to-description
      min-keywords:
      max-keywords:
      min-length:
      max-max:
      max-competitorLength:
      allow-additionParagraph:
      unique:
      competitors-mix:
      check-plagiat:
      is-keyword:
      is-url:
      first-include-others: